server:
  #port: 7970
  port: 9970
spring:
  application:
    name: inter-hsp-txmanager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://hsp-rds.wkmhs.com:3306/internethsp?characterEncoding=UTF-8&useUnicode=true&useSSL=true&serverTimezone=UTC
    username: internethsp
    password: Internethsp@2020
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
#redis 主机
  redis:
    host: hsp-redis.wkmhs.com
  #redis 端口
    port: 6379
  #redis 密码

    password: Wkhsp@2020!@

# TM后台登陆密码
tx-lcn:
  manager:
    admin-key: 123456

    host: 127.0.0.1
    port: 8070

# 开启日志,默认为false
  logger:
   enabled: true
   driver-class-name: ${spring.datasource.driver-class-name}
   jdbc-url: ${spring.datasource.url}
   username: ${spring.datasource.username}
   password: ${spring.datasource.password}
logging:
  level:
    com:
      codingapi:
        txlcn: DEBUG
    org:
      springframework:
        security:
          oauth2: debug  
 #security权限认证配置          
security:
  oauth2:
    resource:
      jwt:
        key-value: client-secret
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url.defaultZone: http://admin:admin@127.0.0.1:9092/eureka/eureka

